name: Render Quarto files and upload

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      files_to_render:
        description: 'Files paths to render'
        required: false
        default: ''
      # Check https://quarto.org/docs/output-formats/all-formats.html for all available formats
      export_format:
        description: 'Formats to export the rendered files to: [revealjs,pdf,html,docx,beamer,ipynb,etc.]'
        required: false
        default: 'revealjs,pdf'

jobs:
  build-upload:
    runs-on: ubuntu-latest

    steps:

    # Download the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Install Quarto
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    # Set env var if not set with all .qmd files
    - name: Set files_to_render
      run: |
        if [ -z "${{ github.event.inputs.files_to_render }}" ]; then
          files=$(find . -name "*.qmd" | tr '\n' ' ')
          echo "files_to_render=$(echo $files)" >> $GITHUB_ENV
        else
          echo "files_to_render=$(echo ${{ github.event.input.files_to_render }})" >> $GITHUB_ENV
        fi

    # Echo files to render paths [debug]
    - name: Echo files to render paths
      run: |
        echo "Files to render: ${{ env.files_to_render }}"

    # Render Quarto files
    - name: Render Quarto files
      run: |
        quarto render ${{ env.files_to_render }} --to ${{ github.event.input.export_format }} --output-dir ${{ github.workspace }}/_build

    # Store the result as artifact
    - name: Store the result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuartoRenderResults
        path: ${{ github.workspace }}/_build
